### ISSUE TITLE
Update Debian version

### ISSUE THREAD

**Issue by robjuz** [thecodingmachine/docker-images-nodejs#13]
## Why?
Debian stretch comes with python 3.5.3

I wanted to use this image with latest expo-cli and got an error because of missing python >= 3.6

## What can we do?
What about a V2 version base on debian buster or bullseye? 

Or maybe building all 3 variants? The current names would stay for the stretch variant to not break compatibility and additional `-stretch`, `-buster` and `-bullseye` variants would be added.

**Comment by mistraloz** [comment]
Hello. stretch version will be deprecated at middle of next year so upgrade is required. 
Upgrade to `buster` or `bullseye` may be a good idea. Also, i would like to add an `alpine` version of this image. 

I suggest : 
- Add 4 tags : `buster`, `bullseye`, `alpine` and `stretch`
- Base the no specific tag to `stretch` for compatibility (until next major version like `v2`)

If you would like to make PR for any of these tags, please do it. I plan to work on that next year but i don't know yet when.

**Comment by moufmouf** [comment]
Hey, working on this right now: https://github.com/thecodingmachine/docker-images-nodejs/pull/20

**Comment by moufmouf** [comment]
We now have a v2 (with only support for bullseye, but the tag contains the distro so there is room to add new distros in the future!)
