### ISSUE TITLE
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

### ISSUE THREAD

**Issue by phareal** [thecodingmachine/docker-images-nodejs#19]
Environment
Platform: Mac M1 ARM
Docker Version: 20.10.16
Node.js Version: v14
Image Tag: thecodingmachine/nodejs:14
Expected Behavior
Build the nuxt js dependencies and run the project

Current Behavior
When trying to run my binary in my docker node:14 image on MacbookM1, I get the following error:

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

Possible Solution
I have no idea, but the lib in question clearly is not here on node:14 ARM64

**Comment by moufmouf** [comment]
Weird.... did you purge your node_modules directory and tried to run an `npm install` again?
It may be possible that you are having old amd64 binaries in your node_modules...

**Comment by phareal** [comment]
Hello same issue with the fix on my side

**Comment by moufmouf** [comment]
Finally closed by #24 \o/
