### ISSUE TITLE
FROM debian:stretch-slim TO node:10

### ISSUE THREAD

**Issue by ErwanLP** [thecodingmachine/docker-images-nodejs#3]
I have a library called 'PhantomJS' on a project called 'qaMachine'
With the tcm-node docker image, the application stops when it tries to use this library. But when i use official node docker image, it work fine.

I solved this issuee by adding 'STARTUP_COMMAND_2: sudo apt-get install -y libfontconfig' in docker-compose file.

It could be a good idea for this image to start FROM nodejs docker image
In this way, the image will have all cool stuff from Node and all cool stuff from TCM.

**Comment by gulien** [comment]
I don't want to use the default NodeJS image, but I'll update the Dockerfile to install this library.
Thanks for the feedback!

**Comment by gulien** [comment]
You should delete your local image using `docker rmi image_name` so you'll use the latest version with `libfontconfig` installed :)
