### ISSUE TITLE
Problem running  thecodingmachine/nodejs:14 on Ubuntu arm  

### ISSUE THREAD

**Issue by phareal** [thecodingmachine/docker-images-nodejs#9]
Hello , i try to run this image on  my vagrant  arm ubuntu  and the build failed with this error
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

info 
Os : Big sur on Apple M1 chip 
vagrant 
provider : parrallels

**Comment by moufmouf** [comment]
Fixed by https://github.com/thecodingmachine/docker-images-nodejs/pull/10

**Comment by moufmouf** [comment]
Reopening, I was wrong, arm64 images not ready yet
